---
title: "Lab Assignment 1"
author: "Joakim Olofsson, Jesper Nyman, Oliver Pahmp, Roma Goussakov"
date: "18 Sep 2019"
output:
  pdf_document:
    keep_md: no
---

***
## Task 1
***

>Task 1.1:

<!-- This will install the package and look up 'rmvnorm' function. (HTML comment) -->
```{r}
install.packages("mixtools")
library(mixtools)
?rmvnorm
```

<!-- Time to generate 1000 realizations from a 2D Gaussian distrubution -->
```{r}
n = 1000 # number of realizations
p = 0.7 # correlation factor
mu = c(2,3) # mean
sigma = c(1,4) # sigma
Cov = matrix(c(1,p*4,p*4,16),nrow=2,ncol=2) # Covariance

X = rmvnorm(n, mu, Cov) # X values

plot(X) # Scatterplot
```

>Task 1.2:

```{r echo=False}
p = 0.6 # Bernoulli distribution parameter
n = 1000

X = matrix(0, nrow=1000,ncol=2)

u1 = c(2,3)
u2 = c(3,2)

sigma_1 = c(0.2,0.6)
sigma_2 = c(0.4,0.3)

p1 = 0.5
p2 = 0.5

Cov_1 = matrix(c(sigma_1[1]*sigma_1[1],p1*sigma_1[1]*sigma_1[2],p1*sigma_1[2]*sigma_1[1],sigma_1[2]*sigma_1[2]),nrow=2,ncol=2)

Cov_2 = matrix(c(sigma_2[1]*sigma_2[1],p2*sigma_2[1]*sigma_2[2],p2*sigma_2[2]*sigma_2[1],sigma_2[2]*sigma_2[2]),nrow=2,ncol=2)

for (i in seq(from=1, to=n, by=1))
{
  z = rbinom(n=1,prob=p,size=1)
  if (z == 1)
  {
    X[i,] = rmvnorm(1, u1, Cov_1) # X values
  }
  else
  {
    X[i,] = rmvnorm(1, u2, Cov_2) # X Values
  }
}

```

>Task 1.3:

```{r}
lambda = c(0.6, 0.4)
Y = mvnormalmixEM(X, c(0.6,0.4))
res1 = Y$mu[[1]] - u1 # Compare difference between means
res2 = Y$mu[[2]] - u2 # Compare diff between means

# There seems to be smaller than 5% difference in means.
```

***
## Task 2
***


```{r}
# Get the mean vectors only? :D
Flower_data = read.table("BlindingIris.txt", as.is= TRUE)
Flower_data = tail(Flower_data,100)

Petal_length = as.numeric(Flower_data$V1)
Petal_width = as.numeric(Flower_data$V2)

mu_length = mean(Petal_length)
mu_width = mean(Petal_width)
length_setosa_versicolor = (4.260+1.462)/2
width_setosa_versicolor = (0.246+1.326)/2
```


